apiVersion: samplecontroller.adieumonks.github.io/v1alpha1
kind: Foo
metadata:
  labels:
    app.kubernetes.io/name: foo-controller-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: foo-sample
spec:
  deploymentName: example-foo
  replicas: 1
